package fr.altiscraft.benjaminloison.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelFireplace extends ModelBase
{
    ModelRenderer one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fiveteen, sixteen, seventeen, eighteen, nineteen, twenty, twentyone, twentytwo, twentythree, twentyfour, twentyfive, twentysix, twentyseven, twentyeight, twentynine, thirty, thirtyone, thirtytwo, thirtythree, thirtyfour, thirtyfive, thirtysix, thirtyseven, thirtyeight;

    public ModelFireplace()
    {
        textureWidth = 32;
        textureHeight = 32;
        one = new ModelRenderer(this, 0, 0);
        one.addBox(0, 0, 0, 4, 2, 2);
        one.setRotationPoint(-5, 9, -8);
        one.setTextureSize(32, 32);
        setRotation(one, 0, 0, 0);
        two = new ModelRenderer(this, 0, 0);
        two.addBox(0, 0, 0, 2, 2, 4);
        two.setRotationPoint(6, 9, 1);
        two.setTextureSize(32, 32);
        setRotation(two, 0, 0, 0);
        three = new ModelRenderer(this, 0, 0);
        three.addBox(0, 0, 0, 2, 2, 4);
        three.setRotationPoint(-8, 9, -5);
        three.setTextureSize(32, 32);
        setRotation(three, 0, 0, 0);
        four = new ModelRenderer(this, 0, 0);
        four.addBox(0, 0, 0, 1, 16, 10);
        four.setRotationPoint(5, 8, -5);
        four.setTextureSize(32, 32);
        setRotation(four, 0, 0, 0);
        five = new ModelRenderer(this, 0, 0);
        five.addBox(0, 0, 0, 4, 2, 2);
        five.setRotationPoint(-5, 9, 6);
        five.setTextureSize(32, 32);
        setRotation(five, 0, 0, 0);
        six = new ModelRenderer(this, 0, 0);
        six.addBox(0, 0, 0, 2, 2, 4);
        six.setRotationPoint(-8, 9, 1);
        six.setTextureSize(32, 32);
        setRotation(six, 0, 0, 0);
        seven = new ModelRenderer(this, 0, 0);
        seven.addBox(0, 0, 0, 4, 2, 2);
        seven.setRotationPoint(1, 9, -8);
        seven.setTextureSize(32, 32);
        setRotation(seven, 0, 0, 0);
        eight = new ModelRenderer(this, 0, 0);
        eight.addBox(0, 0, 0, 12, 16, 1);
        eight.setRotationPoint(-6, 8, -6);
        eight.setTextureSize(32, 32);
        setRotation(eight, 0, 0, 0);
        nine = new ModelRenderer(this, 0, 0);
        nine.addBox(0, 0, 0, 12, 16, 1);
        nine.setRotationPoint(-6, 8, 5);
        nine.setTextureSize(32, 32);
        setRotation(nine, 0, 0, 0);
        ten = new ModelRenderer(this, 0, 0);
        ten.addBox(0, 0, 0, 1, 16, 10);
        ten.setRotationPoint(-6, 8, -5);
        ten.setTextureSize(32, 32);
        setRotation(ten, 0, 0, 0);
        eleven = new ModelRenderer(this, 0, 0);
        eleven.addBox(0, 0, 0, 8, 2, 4);
        eleven.setRotationPoint(-4, 21, 2);
        eleven.setTextureSize(32, 32);
        setRotation(eleven, -0.4537856F, 0.8552113F, 0.0523599F);
        twelve = new ModelRenderer(this, 0, 0);
        twelve.addBox(0, 0, 0, 2, 2, 4);
        twelve.setRotationPoint(6, 9, -5);
        twelve.setTextureSize(32, 32);
        setRotation(twelve, 0, 0, 0);
        thirteen = new ModelRenderer(this, 0, 0);
        thirteen.addBox(0, 0, 0, 4, 2, 2);
        thirteen.setRotationPoint(-2, 18, 6);
        thirteen.setTextureSize(32, 32);
        setRotation(thirteen, 0, 0, 0);
        fourteen = new ModelRenderer(this, 0, 0);
        fourteen.addBox(0, 0, 0, 4, 2, 2);
        fourteen.setRotationPoint(1, 21, 6);
        fourteen.setTextureSize(32, 32);
        setRotation(fourteen, 0, 0, 0);
        fiveteen = new ModelRenderer(this, 0, 0);
        fiveteen.addBox(0, 0, 0, 4, 2, 2);
        fiveteen.setRotationPoint(-5, 21, 6);
        fiveteen.setTextureSize(32, 32);
        setRotation(fiveteen, 0, 0, 0);
        sixteen = new ModelRenderer(this, 0, 0);
        sixteen.addBox(0, 0, 0, 2, 2, 4);
        sixteen.setRotationPoint(-8, 21, 1);
        sixteen.setTextureSize(32, 32);
        setRotation(sixteen, 0, 0, 0);
        seventeen = new ModelRenderer(this, 0, 0);
        seventeen.addBox(0, 0, 0, 2, 2, 4);
        seventeen.setRotationPoint(-8, 18, -2);
        seventeen.setTextureSize(32, 32);
        setRotation(seventeen, 0, 0, 0);
        eighteen = new ModelRenderer(this, 0, 0);
        eighteen.addBox(0, 0, 0, 2, 2, 4);
        eighteen.setRotationPoint(-8, 21, -5);
        eighteen.setTextureSize(32, 32);
        setRotation(eighteen, 0, 0, 0);
        nineteen = new ModelRenderer(this, 0, 0);
        nineteen.addBox(0, 0, 0, 4, 2, 2);
        nineteen.setRotationPoint(-5, 21, -8);
        nineteen.setTextureSize(32, 32);
        setRotation(nineteen, 0, 0, 0);
        twenty = new ModelRenderer(this, 0, 0);
        twenty.addBox(0, 0, 0, 4, 2, 2);
        twenty.setRotationPoint(-2, 18, -8);
        twenty.setTextureSize(32, 32);
        setRotation(twenty, 0, 0, 0);
        twentyone = new ModelRenderer(this, 0, 0);
        twentyone.addBox(0, 0, 0, 4, 2, 2);
        twentyone.setRotationPoint(1, 21, -8);
        twentyone.setTextureSize(32, 32);
        setRotation(twentyone, 0, 0, 0);
        twentytwo = new ModelRenderer(this, 0, 0);
        twentytwo.addBox(0, 0, 0, 2, 2, 4);
        twentytwo.setRotationPoint(6, 21, 1);
        twentytwo.setTextureSize(32, 32);
        setRotation(twentytwo, 0, 0, 0);
        twentythree = new ModelRenderer(this, 0, 0);
        twentythree.addBox(0, 0, 0, 2, 2, 4);
        twentythree.setRotationPoint(6, 18, -2);
        twentythree.setTextureSize(32, 32);
        setRotation(twentythree, 0, 0, 0);
        twentyfour = new ModelRenderer(this, 0, 0);
        twentyfour.addBox(0, 0, 0, 2, 2, 4);
        twentyfour.setRotationPoint(6, 21, -5);
        twentyfour.setTextureSize(32, 32);
        setRotation(twentyfour, 0, 0, 0);
        twentyfive = new ModelRenderer(this, 0, 0);
        twentyfive.addBox(0, 0, 0, 4, 2, 2);
        twentyfive.setRotationPoint(-2, 12, 6);
        twentyfive.setTextureSize(32, 32);
        setRotation(twentyfive, 0, 0, 0);
        twentysix = new ModelRenderer(this, 0, 0);
        twentysix.addBox(0, 0, 0, 4, 2, 2);
        twentysix.setRotationPoint(1, 15, 6);
        twentysix.setTextureSize(32, 32);
        setRotation(twentysix, 0, 0, 0);
        twentyseven = new ModelRenderer(this, 0, 0);
        twentyseven.addBox(0, 0, 0, 4, 2, 2);
        twentyseven.setRotationPoint(-5, 15, 6);
        twentyseven.setTextureSize(32, 32);
        setRotation(twentyseven, 0, 0, 0);
        twentyeight = new ModelRenderer(this, 0, 0);
        twentyeight.addBox(0, 0, 0, 2, 2, 4);
        twentyeight.setRotationPoint(-8, 15, 1);
        twentyeight.setTextureSize(32, 32);
        setRotation(twentyeight, 0, 0, 0);
        twentynine = new ModelRenderer(this, 0, 0);
        twentynine.addBox(0, 0, 0, 2, 2, 4);
        twentynine.setRotationPoint(-8, 12, -2);
        twentynine.setTextureSize(32, 32);
        setRotation(twentynine, 0, 0, 0);
        thirty = new ModelRenderer(this, 0, 0);
        thirty.addBox(0, 0, 0, 2, 2, 4);
        thirty.setRotationPoint(-8, 15, -5);
        thirty.setTextureSize(32, 32);
        setRotation(thirty, 0, 0, 0);
        thirtyone = new ModelRenderer(this, 0, 0);
        thirtyone.addBox(0, 0, 0, 4, 2, 2);
        thirtyone.setRotationPoint(-5, 15, -8);
        thirtyone.setTextureSize(32, 32);
        setRotation(thirtyone, 0, 0, 0);
        thirtytwo = new ModelRenderer(this, 0, 0);
        thirtytwo.addBox(0, 0, 0, 4, 2, 2);
        thirtytwo.setRotationPoint(-2, 12, -8);
        thirtytwo.setTextureSize(32, 32);
        setRotation(thirtytwo, 0, 0, 0);
        thirtythree = new ModelRenderer(this, 0, 0);
        thirtythree.addBox(0, 0, 0, 4, 2, 2);
        thirtythree.setRotationPoint(1, 15, -8);
        thirtythree.setTextureSize(32, 32);
        setRotation(thirtythree, 0, 0, 0);
        thirtyfour = new ModelRenderer(this, 0, 0);
        thirtyfour.addBox(0, 0, 0, 2, 2, 4);
        thirtyfour.setRotationPoint(6, 15, 1);
        thirtyfour.setTextureSize(32, 32);
        setRotation(thirtyfour, 0, 0, 0);
        thirtyfive = new ModelRenderer(this, 0, 0);
        thirtyfive.addBox(0, 0, 0, 2, 2, 4);
        thirtyfive.setRotationPoint(6, 12, -2);
        thirtyfive.setTextureSize(32, 32);
        setRotation(thirtyfive, 0, 0, 0);
        thirtysix = new ModelRenderer(this, 0, 0);
        thirtysix.addBox(0, 0, 0, 2, 2, 4);
        thirtysix.setRotationPoint(6, 15, -5);
        thirtysix.setTextureSize(32, 32);
        setRotation(thirtysix, 0, 0, 0);
        thirtyseven = new ModelRenderer(this, 0, 0);
        thirtyseven.addBox(0, 0, 0, 4, 2, 2);
        thirtyseven.setRotationPoint(1, 9, 6);
        thirtyseven.setTextureSize(32, 32);
        setRotation(thirtyseven, 0, 0, 0);
        thirtyeight = new ModelRenderer(this, 0, 0);
        thirtyeight.addBox(0, 0, 0, 8, 2, 4);
        thirtyeight.setRotationPoint(-4, 21, 0);
        thirtyeight.setTextureSize(32, 32);
        setRotation(thirtyeight, -0.5934119F, 0.1919862F, 0);
    }

    public void renderAll()
    {
        one.render(0.0625F);
        two.render(0.0625F);
        three.render(0.0625F);
        four.render(0.0625F);
        five.render(0.0625F);
        six.render(0.0625F);
        seven.render(0.0625F);
        eight.render(0.0625F);
        nine.render(0.0625F);
        ten.render(0.0625F);
        eleven.render(0.0625F);
        twelve.render(0.0625F);
        fourteen.render(0.0625F);
        fiveteen.render(0.0625F);
        sixteen.render(0.0625F);
        twelve.render(0.0625F);
        thirteen.render(0.0625F);
        fourteen.render(0.0625F);
        fiveteen.render(0.0625F);
        sixteen.render(0.0625F);
        seventeen.render(0.0625F);
        eighteen.render(0.0625F);
        nineteen.render(0.0625F);
        twenty.render(0.0625F);
        twentyone.render(0.0625F);
        twentytwo.render(0.0625F);
        twentythree.render(0.0625F);
        twentyfour.render(0.0625F);
        twentyfive.render(0.0625F);
        twentysix.render(0.0625F);
        twentyseven.render(0.0625F);
        twentyeight.render(0.0625F);
        twentynine.render(0.0625F);
        thirty.render(0.0625F);
        thirtyone.render(0.0625F);
        thirtytwo.render(0.0625F);
        thirtythree.render(0.0625F);
        thirtyfour.render(0.0625F);
        thirtyfive.render(0.0625F);
        thirtysix.render(0.0625F);
        thirtyseven.render(0.0625F);
        thirtyeight.render(0.0625F);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}